### ISSUE TITLE
Can anyone solve the image upload issue in my website 

### ISSUE THREAD

**Issue by Nababratadeb-NITA** [Nababratadeb-NITA/Render-Hub#1] opened 2023-05-30 13:10 UTC
i did this in new NextJS 13 (frontend, backrnd both) in model folder i define the schema and in /api/prompt/next/route/js i wrote the post route api and i used this in crteate-prompt/page.jsx file 

Can anyone please check and find the issue? i'd be very greatfull to him/her.

**Comment by amitesh-183** [comment] 2023-05-30 15:31
can you assign it to me, I can try

**Comment by Nababratadeb-NITA** [comment] 2023-05-30 16:29
@amitesh-183  yeah sure brother

**Comment by amitesh-183** [comment] 2023-05-30 16:38
> 

ok by going through the post api: you "**cloudnary as v2**" but used cloudnary instead, I think
![Screenshot 2023-05-30 211103](https://github.com/Nababratadeb-NITA/Render-Hub/assets/80208506/ccde11ad-201e-463b-a890-18c3ff770a4f)

**Comment by Samarth-Dengre** [comment] 2023-05-30 17:09
Is the issue solved

**Comment by amitesh-183** [comment] 2023-05-30 17:28
> Is the issue solved

I am working on it

**Comment by Nababratadeb-NITA** [comment] 2023-05-31 04:31
> > 
> 
> ok by going through the post api: you "**cloudnary as v2**" but used cloudnary instead, I think
> ![Screenshot 2023-05-30 211103](https://github.com/Nababratadeb-NITA/Render-Hub/assets/80208506/ccde11ad-201e-463b-a890-18c3ff770a4f)
> 

Yeah is there the issue?

**Comment by Nababratadeb-NITA** [comment] 2023-05-31 04:33
@amitesh-183 I want to convert the image into url so that I can store that url as a string in mongo db

**Comment by Samarth-Dengre** [comment] 2023-05-31 06:22
@Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?

**Comment by Nababratadeb-NITA** [comment] 2023-05-31 06:41
> @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?

I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file

**Comment by amitesh-183** [comment] 2023-05-31 06:42
> > @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?
> 
> I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file

I have made a pull request you can try, It might solve the issue

**Comment by Samarth-Dengre** [comment] 2023-05-31 06:55
> > @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?
> 
> I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file

You want image as string or you want its URL when image is uploaded on cloudinary.

**Comment by Nababratadeb-NITA** [comment] 2023-05-31 13:33
Hey are you faced access denied issue while logging in ? Do not know why I'm facing this issue now

**Comment by Nababratadeb-NITA** [comment] 2023-06-01 19:51
hey @Samarth-Dengre  are you facing any problem while signing in ?

**Comment by Nababratadeb-NITA** [comment] 2023-06-01 19:59
> > > @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?
> > 
> > 
> > I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file
> 
> You want image as string or you want its URL when image is uploaded on cloudinary.

hey @Samarth-Dengre  can you find the issue and fix that ?

**Comment by Samarth-Dengre** [comment] 2023-06-02 08:36
> > > > @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?
> > > 
> > > 
> > > I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file
> > 
> > 
> > You want image as string or you want its URL when image is uploaded on cloudinary.
> 
> hey @Samarth-Dengre can you find the issue and fix that ?

what issue?

**Comment by Nababratadeb-NITA** [comment] 2023-06-02 08:40
> > > > > @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?
> > > > 
> > > > 
> > > > I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file
> > > 
> > > 
> > > You want image as string or you want its URL when image is uploaded on cloudinary.
> > 
> > hey @Samarth-Dengre can you find the issue and fix that ?
> 
> what issue?

So I want to store an image in my mongo database but it is showing internal error when I asked chatgpt it said that in schema i have written image type as string but from client side it returns an image 

So it's you choice either you can convert it into the string and then store it or do in your own way whatever suits you.

**Comment by Samarth-Dengre** [comment] 2023-06-02 09:08
> > > > > > @Nababratadeb-NITA  I can help to solve the issue. Can you brief me about what exactly the problem is?
> > > > > 
> > > > > 
> > > > > I want while posting the data to mongodb database the image should be converted to string as I define image as string in model schema file
> > > > 
> > > > 
> > > > You want image as string or you want its URL when image is uploaded on cloudinary.
> > > 
> > > 
> > > hey @Samarth-Dengre can you find the issue and fix that ?
> > 
> > 
> > what issue?
> 
> So I want to store an image in my mongo database but it is showing internal error when I asked chatgpt it said that in schema i have written image type as string but from client side it returns an image
> 
> So it's you choice either you can convert it into the string and then store it or do in your own way whatever suits you.

ok, I will look into it.

**Comment by Samarth-Dengre** [comment] 2023-06-02 12:34
can you share a sample .env file
Also tell me where you want this image to be shown.
I have converted image to string.

The card now looks like this
![Screenshot (184)](https://github.com/Nababratadeb-NITA/Render-Hub/assets/103602874/55f0a392-daea-42f3-a609-960d2a86e916)

**Comment by Samarth-Dengre** [comment] 2023-06-03 06:17
@Nababratadeb-NITA please verify and merge my PR

**Comment by Nababratadeb-NITA** [comment] 2023-06-03 12:11
> can you share a sample .env file Also tell me where you want this image to be shown. I have converted image to string.
> 
> The card now looks like this ![Screenshot (184)](https://user-images.githubusercontent.com/103602874/242905269-55f0a392-daea-42f3-a609-960d2a86e916.png)

GOOGLE_ID = 957443223144-gs0u91pql5srun06tjq3rmho9i2lkaea.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET = client secrect

CLOUDINARY_CLOUD_NAME="djzml9nau"
CLOUDINARY_API_KEY="547222258672826"
CLOUDINARY_API_SECRET="secrect"

NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_URL_INTERNAL=http://localhost:3000
NEXTAUTH_SECRECT= b34da07323f7ab87f02f6474188343b145719eb56a9a68de4ae52c247295cbbe5fea79f72c985d13c5e4e137da03ef8ce6c7e5d93b3898ce37594999ef23535f

**Comment by Nababratadeb-NITA** [comment] 2023-06-03 12:12
> @Nababratadeb-NITA please verify and merge my PR

sure thank you

**Comment by Samarth-Dengre** [comment] 2023-06-03 12:20
> > @Nababratadeb-NITA please verify and merge my PR
> 
> sure thank you

is it working according to expectations

**Comment by Nababratadeb-NITA** [comment] 2023-06-03 15:41
> > > @Nababratadeb-NITA please verify and merge my PR
> > 
> > 
> > sure thank you
> 
> is it working according to expectations

yea its working thank you very much brother 

but after pressing upload button it shows me one error 

TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

do you know why and how to solve this?

**Comment by Samarth-Dengre** [comment] 2023-06-03 17:14
It's working fine on my side. 
Tell me the steps to regenerate the error.

**Comment by Nababratadeb-NITA** [comment] 2023-06-03 19:41
> It's working fine on my side. Tell me the steps to regenerate the error.

ok now its working

**Closed as completed** 2023-06-19 14:28 UTC
Labels: bug, good first issue
